### ISSUE TITLE
Создать скетч GUI ПП под ранее созданную БД (магазин канцтоваров). Выполнить до 23.10.2020 18:00

### ISSUE THREAD

**Issue by bespalova-m-a** [IDC-02-01/lazarevme#4]
Студент(ка): Лазарев Максим Евгеньевич

**Comment by Lazarevme** [comment]
![image](https://user-images.githubusercontent.com/72433593/104718929-bddd8e00-573c-11eb-848a-084929c737da.png)

**Comment by bespalova-m-a** [comment]
работа принята
