### ISSUE TITLE
Построить диаграмму классов ИС для ранее нормализованной БД, в соответствии с SOLID

### ISSUE THREAD

**Issue by bespalova-m-a** [IDC-02-01/lazarevme#5]
Студент(ка): Лазарев Максим Евгеньевич
Выполнить до 16.10.2020 18:00

**Comment by Lazarevme** [comment]
![Снимок](https://user-images.githubusercontent.com/72433593/104715672-e44cfa80-5737-11eb-8bd1-2f196e88b2e1.PNG)

**Comment by bespalova-m-a** [comment]
Работа принята
